### ISSUE TITLE
gem install not working correctly

### ISSUE THREAD

**Issue by AndrewCopeland** [Venafi/vcert-ruby#12]
When installing using the command
`gem install vcert`

The `utils` folder is not being created in the vcert/lib folder.

**Comment by tr1ck3r** [comment]
Hi @AndrewCopeland, we were just able to publish our gem for the first time earlier today and are still working out a few kinks with it.  Please bear with us, I expect we'll be able to resolve this in the next day or two.

**Comment by mr-tron** [comment]
Missed one file in gemspec. Fixed in version 0.1.1
